# Generated by Django 2.2.6 on 2019-10-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
