# Generated by Django 2.2.5 on 2019-10-16 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0002_remove_profile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_experience', models.TextField(max_length=15)),
                ('company', models.TextField(max_length=15)),
                ('started', models.IntegerField(default=2019)),
                ('finished', models.IntegerField(default=2020)),
                ('job', models.TextField(max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_chainedout.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.TextField(max_length=15)),
                ('title', models.TextField(max_length=15)),
                ('started', models.IntegerField(default=2019)),
                ('finished', models.IntegerField(default=2020)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_chainedout.Profile')),
            ],
        ),
    ]
