# Generated by Django 2.2.5 on 2019-10-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0004_auto_20191016_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='profile',
            new_name='user',
        ),
    ]
