# Generated by Django 2.2.1 on 2019-10-12 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_chainedout', '0005_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.TextField(blank=True, max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('jobIds', models.IntegerField(blank=True)),
                ('phone', models.IntegerField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
