# Generated by Django 2.2.1 on 2019-10-12 22:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_chainedout', '0006_auto_20191012_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileForm',
            new_name='Profile',
        ),
    ]
