# Generated by Django 2.2.5 on 2019-10-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0006_auto_20191018_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='finished',
            new_name='edu_finished',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='started',
            new_name='edu_started',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='finished',
            new_name='exp_finished',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='started',
            new_name='exp_started',
        ),
    ]
