# Generated by Django 2.2.6 on 2019-11-22 12:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0007_auto_20191122_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 12, 2, 33, 891046, tzinfo=utc)),
        ),
    ]
