# Generated by Django 2.2.6 on 2019-11-26 10:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0009_auto_20191122_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 10, 42, 11, 997391, tzinfo=utc)),
        ),
    ]
