# Generated by Django 2.2.5 on 2019-10-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0009_auto_20191024_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='entity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='work_experience',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(max_length=500),
        ),
    ]
