# Generated by Django 2.2.1 on 2019-10-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0010_auto_20191015_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='achivements',
            new_name='achievements',
        ),
    ]
