# Generated by Django 2.2.6 on 2019-11-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0011_auto_20191126_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
