# Generated by Django 2.2.6 on 2019-11-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0015_auto_20191126_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
