# Generated by Django 2.2.6 on 2019-11-27 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0016_remove_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cooments', to='web_chainedout.Post'),
        ),
    ]
