# Generated by Django 2.2.6 on 2019-11-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0017_auto_20191127_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='texto',
        ),
    ]
