# Generated by Django 2.2.6 on 2019-11-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0020_auto_20191127_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=500, unique_for_date='published'),
        ),
    ]
