# Generated by Django 2.2.6 on 2019-11-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0006_post_likes'),
        ('web_chainedout', '0021_auto_20191127_1158'),
    ]

    operations = [
    ]
