# Generated by Django 2.2.6 on 2019-12-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0022_merge_20191127_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.IntegerField(default=0),
        ),
    ]
