# Generated by Django 2.2.6 on 2019-12-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0023_profile_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organization',
        ),
    ]
