# Generated by Django 2.2.6 on 2019-12-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0025_profile_organizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='organizations',
            new_name='organization',
        ),
    ]
