# Generated by Django 2.2.6 on 2019-12-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0026_auto_20191207_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organization',
        ),
    ]
