# Generated by Django 2.2.6 on 2019-12-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0027_remove_profile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.IntegerField(default=1),
        ),
    ]
