# Generated by Django 2.2.5 on 2019-12-11 00:49

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_chainedout', '0029_privatemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('browser', models.TextField()),
                ('os', models.TextField()),
                ('device', models.TextField()),
                ('user', models.ManyToManyField(blank=True, null=True, related_name='device_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
