# Generated by Django 2.2.5 on 2019-12-11 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0030_devicelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='device_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
