# Generated by Django 2.2.5 on 2019-12-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0031_auto_20191211_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelog',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='devicelog',
            name='device',
        ),
        migrations.RemoveField(
            model_name='devicelog',
            name='os',
        ),
        migrations.AddField(
            model_name='devicelog',
            name='browser_family',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='browser_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='device_family',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='os_family',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='os_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
