# Generated by Django 2.2.5 on 2019-12-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_chainedout', '0033_groupinviterequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupInviteRequest',
        ),
    ]
